[package]
name = "try_rust"
version = "0.1.0"
authors = ["nnnkkk7 <kurodanaoki0711pana@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ferris-says = "0.2"